item = ['Al Amin', 'Polok', 'Aminul', 'Mohimen']
print(item)
print(item[:2])
item.append('Jahid')
print(item)
item.insert(3,'Shihab')
print(item)
item.remove('Shihab')
print(item)
print('Al Amin' in item)
item.sort(reverse=True)
uni = ['NSU', 'IUB', 'AIUB']
print(item)
# print(item+uni)
# print(dir(item))
print(item[-3:])